import { Lab } from '@/types/tip';

export const LAB_BUR_01: Lab = {
  id: 'tp-bur-01-corinne',
  titre: "Sauvetage du manifeste d'arrivages maritimes de Corinne & Fiscalité Antilles",
  description: "Dépannage critique du classeur Excel de suivi des conteneurs portuaires de Corinne (Facturation & Douane). Rétablissement des codes postaux sur 5 chiffres, élimination des erreurs #N/A via SUPPRESPACE/SIERREUR, calcul automatisé de l'Octroi de mer (8.5%) et de la TVA Guadeloupe (8.5%) avec références semi-absolues ($), et figeage des volets.",
  domaine: 'bureautique',
  palier: 'Palier 1',
  points_total: 200,
  points_auto_validation: 100,
  badge_id: 'corinne_savior',
  ticket_id: 'TCK-101',
  fichier_modele_nom: 'KLF_Manifeste_Arrivages_Corinne_BRUT.xlsx',
  fichier_modele_url: '/api/lab/download-sample?labId=tp-bur-01-corinne',
  duree_estimee: '1h30',
  statut: 'ouvert',
  objectifs: [
    "Diagnostiquer et corriger les ruptures de recherche matricielle générant des erreurs #N/A.",
    "Intégrer les taux fiscaux locaux des Antilles (Octroi de mer 8.5% et TVA Guadeloupe 8.5%).",
    "Normaliser les codes postaux sur 5 positions sans perte des zéros non significatifs.",
    "Sécuriser la duplication des formules par l'usage rigoureux des références absolues et semi-absolues ($).",
    "Optimiser l'ergonomie de lecture sur de volumineux classeurs d'entreprise (Figeage des volets).",
  ],
  consignes_etapes: [
    "Téléchargez le classeur brut KLF_Manifeste_Arrivages_Corinne_BRUT.xlsx via le bouton ci-contre.",
    "Ouvrez le fichier dans votre logiciel tableur habituel (Microsoft Excel, LibreOffice Calc ou Google Sheets).",
    "Sur la colonne Code Postal (Col E), appliquez un format texte ou utilisez une formule =TEXTE(cellule; \"00000\") afin que les codes postaux à 5 chiffres (notamment ceux débutant par 0 ou 971) soient préservés sans troncature.",
    "Sur la colonne Frais Transit (Col G), résolvez les erreurs #N/A en éliminant les espaces superflus avec =SUPPRESPACE(...) et sécurisez le retour avec =SIERREUR(...).",
    "Sur les colonnes Octroi de mer (Col H) et TVA 8.5% (Col I), construisez une formule dynamique référençant les cellules de taux de l'en-tête ($H$2 et $I$2) avec le symbole $ pour bloquer la ligne lors de l'étirement.",
    "Sur la colonne Total TTC (Col J), additionnez la Base HT, l'Octroi de mer et la TVA pour chaque ligne.",
    "Activez le figeage des volets sur la ligne d'en-tête (Ligne 3) afin de conserver les titres visibles lors du défilement vertical.",
    "Enregistrez votre classeur au format .xlsx et glissez-le dans la zone d'auto-audit pour valider vos jalons.",
  ],
  jalons: [
    {
      id: 'm1_postal_codes',
      ordre: 1,
      titre: 'Intégrité des codes postaux (5 caractères)',
      description: 'Tous les codes postaux des destinataires doivent comporter 5 caractères (ex: 97122, 01234), formatés en texte sans troncature du zéro initial.',
      points: 20,
      critereAudit: 'Vérification de la présence de 5 caractères textuels sur l\'ensemble des lignes de données.',
    },
    {
      id: 'm2_supprespace_na',
      ordre: 2,
      titre: 'Éradication des erreurs #N/A & SUPPRESPACE',
      description: 'Zéro cellule #N/A résiduelle sur les frais de transit. Utilisation validée de SUPPRESPACE ou SIERREUR.',
      points: 20,
      critereAudit: 'Détection d\'aucune erreur #N/A et détection de formules nettoyant les espaces superflus.',
    },
    {
      id: 'm3_octroi_mer',
      ordre: 3,
      titre: 'Calcul dynamique de l\'Octroi de mer (8.5%)',
      description: 'Formule dynamique calculant 8.5% de la base HT en s\'appuyant sur une référence bloquée ($) vers le taux d\'en-tête.',
      points: 20,
      critereAudit: 'Formule détectée avec multiplication par 8.5% ou référence absolue $H$2, montants exacts.',
    },
    {
      id: 'm4_tva_guadeloupe',
      ordre: 4,
      titre: 'Calcul dynamique de la TVA locale (8.5%)',
      description: 'Formule dynamique calculant la TVA locale de 8.5% sur la base HT avec référence semi-absolue.',
      points: 20,
      critereAudit: 'Formule détectée avec multiplication par 8.5% ou référence absolue $I$2, montants exacts.',
    },
    {
      id: 'm5_freeze_total',
      ordre: 5,
      titre: 'Figeage des volets & Total TTC douanier',
      description: 'La ligne d\'en-tête doit être figée (split/freeze view) et le total général TTC doit concorder avec le manifeste officiel.',
      points: 20,
      critereAudit: 'Vérification du gel des volets (Freeze Panes) et de la concordance de la somme générale TTC.',
    },
  ],
};

export const ALL_LABS: Lab[] = [
  LAB_BUR_01,
  {
    id: 'tp-bur-02-elodie',
    titre: "Gabarit DSI officiel KLF & Publipostage RH sans décalage",
    description: "Conception du modèle officiel .dotx selon la charte graphique DSI KLF et exécution de la campagne de publipostage Word de 60 convocations médicales pour Élodie avec formatage monétaire et gestion des sauts de section.",
    domaine: 'bureautique',
    palier: 'Palier 1',
    points_total: 150,
    points_auto_validation: 75,
    badge_id: 'rh_mailmerge_ace',
    ticket_id: 'TCK-103',
    fichier_modele_nom: 'KLF_Modele_Convocations_RH_BRUT.docx',
    fichier_modele_url: '#',
    duree_estimee: '1h30',
    statut: 'a_venir',
    objectifs: [
      "Créer un modèle Word d'entreprise (.dotx) avec styles Titre 1 et Titre 2.",
      "Gérer le saut de section avec page paysage pour les tableaux d'inventaire.",
      "Effectuer un publipostage sans décalage de saut de ligne.",
    ],
    consignes_etapes: [],
    jalons: [],
  },
  {
    id: 'tp-net-01-zebra',
    titre: "Diagnostic d'adressage IPv4 statique & Dépannage imprimante Zebra ZT410",
    description: "Rétablissement de la connectivité réseau de l'imprimante thermique du quai suite à bascule en adresse APIPA non routable (169.254.x.x). Diagnostic en ligne de commande et réservation DHCP.",
    domaine: 'reseau',
    palier: 'Palier 2',
    points_total: 200,
    points_auto_validation: 100,
    badge_id: 'quai_tutor_pro',
    ticket_id: 'TCK-105',
    fichier_modele_nom: 'KLF_Topology_Quai_Jarry.pka',
    fichier_modele_url: '#',
    duree_estimee: '2h00',
    statut: 'a_venir',
    objectifs: [
      "Identifier une adresse APIPA et interpréter les voyants réseau.",
      "Configurer une adresse IP fixe hors plage dynamique DHCP.",
      "Tester la connectivité par couches du modèle OSI.",
    ],
    consignes_etapes: [],
    jalons: [],
  },
];

export function getLabById(id: string): Lab | undefined {
  return ALL_LABS.find((l) => l.id === id);
}
